### ISSUE TITLE
 Can you share the operation steps instruction? 

### ISSUE THREAD

**Issue by psiydown** [StefanoBerti/metrabs_to_onnx#1]
Have you succeeded in accelerating with metrabs based on TensorRT? Can you share the operation steps instruction? Thank you very much!

**Comment by psiydown** [comment]
Hi @StefanoBerti Thank you for your reply. I tested your AR project. I hope you can answer the following questions:

1.Run models/metrabs_ trt/utils/extract_ onnxs_ from_ metrabs. py

Error:
Traceback (most recent call last):
File "D:\python\scripts\AR-main\models\metrabs_trt\utils\extract_onnxs_from_metrabs.py", line 134, in <module>
pred2d_ metrab, _ = metrab_ mod(tf.cast(pred, tf.float16))
NameError: name 'pred' is not defined

2.Run models/metrabs_ trt/assets/pytorch-YOLOv4/demo_ pytorch2onnx. py

Tips:
Please run this way:
python demo_ onnx. py <weight_ file> <image_ path> <batch_ size> <n_ classes> <IN_ IMAGE_ H> <IN_ IMAGE_ W>

Can you tell me the correct parameters? If my official parameters are:
demo_ pytorch2onnx. py yolov4. pth image. png 8 80 416 416

Error:
File "d:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_ state_ dict
raise RuntimeError('Error(s) in loading state_ dict for {}:\n\t{}'. format(RuntimeError: Error(s) in loading state_ dict for Yolov4

3.Can you help me find the problem? Or share the converted model and send it to my email: pansi@qq.com. Thank you very much!

4.My environment is:
Windows8.1
Anaconda2021.11
Python3.9
Tensorrt-8.2 (version less than 8.2 does not support windows using Python?)
pip install onnx
pip install onnxruntime
And have installed the required software according to your instructions, my environment correct?

**Comment by StefanoBerti** [comment]
Hi,
1) The error happens when checking the model consistency, but the onnx of the BackBone and the Heads have already been extracted
2) YoloV4 is trained with 80 classes and images with dimension 256x256. With this parameters you should have no problem. You also need to give the path to an image with the same dimension of the input. In my case the command was
`python demo_pytorch2onnx.py C:\Users\sberti\PycharmProjects\AR\models\metrabs_trt\models\raws\yolov4-pytorch\yolov4.pth C:\Users\sberti\PycharmProjects\AR\models\metrabs_trt\assets\crop.png 1 80 256 256`
3) In case you don't succeed I can send you the onnx/engine files
I know that the code is not so clean and some minor modifications are needed, sorry about that!

**Comment by psiydown** [comment]
Hi @StefanoBerti The onnx of the BackBone and the Heads have already been extracted, But onnx of Yolo still can't. I hope to send onnx / engine to me pansi@qq.com. Thank you!

**Comment by StefanoBerti** [comment]
@psiydown [here](https://drive.google.com/file/d/1nMaYjmtWqWXy_MJlSaKiZgxIaW9hbG0A/view?usp=sharing) you go :)

**Comment by psiydown** [comment]
Hi @stefanoberti I've tried for a few days and can run. However, the frame rate is only 2 FPS, and the accuracy is relatively low compared with the original model. When there is no one on the camera, the person is still recognized in the middle, and some occlusion can't detect person. I don't know what I did wrong. My steps are as follows:

1. Run models/metabs_ trt/utils/create_ engine. py
`Error Code 1: Cuda Driver (invalid device context)`
However, I delete the following two lines and can run (correct?):
```
cfx = cuda. Device(0). make_ context()
stream = cuda. Stream()
```

2. bbone convert onnx model I use https://github.com/onnx/tensorflow-onnx
bbone create engine uses: models/metabs_ trt/utils/create_ engine.py  (correct?)

3.main. py use "heads_engine_path": 'models/metabs_ trt/models/signature/metrab_ head'
I use the raw "metrab_ head" (correct?)

4. My graphics card is GTX1060 and does not support FP16. I'm not sure if this is the reason for slow recognition and low accuracy. but I use trtexec.exe to INT8 mode, can't detect person.
Can you tell me the model of your graphics card and the construction environment?

5. I hope you send me your TRT engine file to try, thank you!

**Comment by StefanoBerti** [comment]
Hi @psiydown!
1) Are you sure to have CUDA installed in the correct way? I am not an expert of this kind of stuff btw, but if you can't initialize a Cuda driver then I think that you could have trouble when building the engine
2) If the engine is built without errors, then yes I guess
3) Yes, the MetrABS heads run without TensorRT
4) I have compared the results with FP32 and FP16 and they are almost equal. I am using a Nvidia RTX 2080. Are you doing the same preprocessing/postprocessing step as in [https://github.com/StefanoBerti/AR/blob/main/models/metrabs_trt/hpe.py](https://github.com/StefanoBerti/AR/blob/main/models/metrabs_trt/hpe.py)? (Especially the homography part between Yolo and the BackBone)
5) Which one?

**Comment by psiydown** [comment]
Hi @StefanoBerti !
1. I tried CUDA-10.2, 10.3, 10.4, and installed cuDNN-11.3 and Tensorrt-8.2, but the results are the same. Which version do you use?

2. I hope you send "yolo16. trt" and "bbone16.trt" to me for test, thank you!

**Comment by StefanoBerti** [comment]
I do have CUDA-11.2 and TensorRT 8.2.2.1.
[bbone16.trt](https://drive.google.com/file/d/1NEf5IrsGMaoCF-gqg1zqqJT-kJ6GsXYB/view?usp=sharing)
[yolo16.trt](https://drive.google.com/file/d/188p32HLtRidfdi8CuU37alGlpPp1Nu_V/view?usp=sharing)
Let me know if they work!

**Comment by psiydown** [comment]
Hi @StefanoBerti !
Use your engine:
```
[02/24/2022-00:30:53] [TRT] [E] 6: The engine plan file is generated on an 
incompatible device, expecting compute 6.1 got compute 7.5, please rebuild.
```
Unfortunately, it can't run in my system. It should be caused by the compute difference of my graphics card, and the fact that it doesn't support FP16. Also, the TRT engine file built in my system is twice as large size as yours, which is incorrect. I want to build a compatible INT8 engine, but need calibration, I don't know how to get the required calibration files.

FP16 mode Build engine:
```
[02/24/2022-00:43:06] [W] [TRT] Half2 support requested on hardware without 
native FP16 support, performance will be negatively affected.
```
INT8 mode build engine:
```
Error Code 4: Internal Error 
(Calibration failure occurred with no scaling factors detected. This could bedue to no int8 calibrator
 or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
```

**Comment by StefanoBerti** [comment]
Hi @psiydown, in my computer that engine works, anyway it seems like you need to extract the ONNX and build the engine on your system. If you have any problem with my code you can open an issue [here](https://github.com/StefanoBerti/AR), which is where I moved everything and where things are organized better ( I will delete this repo). Thank you!
